version: "3.1"
services:
  db:
    image: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT:-5432}:5432
  adminer:
    depends_on:
      - db
    image: adminer
    ports:
      - ${ADMINER_PORT:-8080}:8080
volumes:
  db-data: